### ISSUE TITLE
enable differentiation / more granular control of  managing versions of parent & submodules

### ISSUE THREAD

**Issue by frko** [q3769/semver-maven-plugin#4]
While bumping my parent project for a next iteration it also bumps the version for all submodules, while I only want to modify a single one. It would be convenient if it would be able to either only bump the parent or a set of sub-modules by inclusion/exclusion.

The plugin is wrongfully updating all submodules with the same change while I only desire the parent version to be set to, I think it is not correct to assume that parent & sub module versions always simultaneously change.

Another good addition would be to support the ci/cd friendly properties, like $revision

**Comment by q3769** [comment]
To keep it simple, the actual change on POM file's version value is done by hard-coding and using another Maven plugin "versions-maven-plugin" as in here - https://github.com/q3769/semver-maven-plugin/blob/c10290754927594ccd27da3e7a54d62bb2ae541c/src/main/java/qt/maven/plugins/semver/SemverMojo.java#L95

Would very much like to keep things simple if possible. As is now, though, if you run this plugin inside a submodule and use that submodule's POM file, doesn't it only change that submodule's version alone?

**Comment by q3769** [comment]
sorry i just saw your point of 

> The plugin is wrongfully updating all submodules with the same change while I only desire the parent version to be set to, I think it is not correct to assume that parent & sub module versions always simultaneously change.

it's strange because, per the versions-maven-plugin's doc https://www.mojohaus.org/versions-maven-plugin/set-mojo.html#processAllModules, "processAllModules" should be "false" by default. that means it should not have changed the child modules' versions.
